services:
  - type: web
    name: kidrocket-designer-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here:
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: kidrocket-db
    #     property: connectionString
